In [1]:
import numpy as np
import pandas as pd
from glob import glob

In [2]:
indexes = glob('/storage/users/g-and-n/plates/tabular_indexes/*')

In [3]:
idx_dfs = [pd.read_csv(ind).groupby(['Plate','Metadata_broad_sample', 'Image_Metadata_Well']).count()['ObjectNumber'] for ind in indexes]

In [4]:
idx_dfs = [idx_df.reset_index() for idx_df in idx_dfs]

In [5]:
platemaps = pd.concat(idx_dfs).groupby('Metadata_broad_sample').agg(lambda l: ','.join([str(x)for x in l]))

In [6]:
matches = platemaps['Plate'].unique()

In [7]:
uniq_mch = np.unique([set(m.split(',')) for m in matches if len(m.split(','))<100])

In [8]:
uniq, cnts = np.unique([len(m) for m in uniq_mch], return_counts=True)

In [9]:
plt_n = [len(set.union(*[u for u in uniq_mch if len(u)==s])) for s in uniq]

In [10]:
plt_n_lte = [len(set.union(*[u for u in uniq_mch if len(u)<=s])) for s in uniq]
plt_n_gte = [len(set.union(*[u for u in uniq_mch if len(u)>=s])) for s in uniq]

In [11]:
all_p=set.union(*uniq_mch)

In [12]:
plt_n_lte_c = [len(all_p-set.union(*[u for u in uniq_mch if len(u)<=s])) for s in uniq]
plt_n_gte_c = [len(all_p-set.union(*[u for u in uniq_mch if len(u)>=s])) for s in uniq]

In [13]:
plt_n_lte_cp = [dict(zip(*np.unique(
    [len(ut-set.union(*[u for u in uniq_mch if len(u)<=s])) for ut in uniq_mch if len(ut)>s],
    return_counts=True))) 
                     for s in uniq]
plt_n_gte_cp = [dict(zip(*np.unique(
    [len(ut-set.union(*[u for u in uniq_mch if len(u)>=s])) for ut in uniq_mch if len(ut)<s],
    return_counts=True))) 
                     for s in uniq]

In [14]:
res = pd.DataFrame({'Size':uniq,
                    'Count':cnts,
                    'Unique Plates':plt_n,
                    'Aggragate <=s':zip(plt_n_lte,plt_n_lte_c,plt_n_lte_cp),
                    'Aggragate >=s':zip(plt_n_gte,plt_n_gte_c,plt_n_gte_cp)})
res.set_index('Size')

,Count,Unique Plates,Aggragate <=s,Aggragate >=s
Size,,,,
1,7,7,"(7, 399, {0: 14, 1: 3, 2: 3, 3: 27, 4: 81, 6: ...","(406, 0, {})"
2,13,14,"(14, 392, {0: 7, 1: 4, 2: 2, 3: 22, 4: 80, 6: ...","(406, 0, {0: 7})"
3,33,71,"(71, 335, {0: 4, 1: 8, 4: 70, 6: 4, 7: 3, 8: 6})","(406, 0, {0: 20})"
4,82,324,"(355, 51, {3: 1, 4: 1, 6: 4, 7: 2, 8: 5})","(375, 31, {0: 33, 1: 3, 2: 6, 3: 11})"
6,4,19,"(374, 32, {1: 2, 2: 2, 3: 1, 4: 1, 7: 1, 8: 2})","(55, 351, {0: 1, 1: 7, 2: 13, 3: 33, 4: 81})"
7,3,21,"(385, 21, {0: 1, 1: 1, 2: 2, 8: 2})","(55, 351, {0: 5, 1: 7, 2: 13, 3: 33, 4: 81})"
8,6,48,"(406, 0, {})","(48, 358, {0: 7, 1: 7, 2: 13, 3: 33, 4: 81, 7:..."

In [15]:
pd.set_option('max_colwidth', 400)

In [16]:
uniq_mch

array([{'25581', '25580', '25583', '25579'}, {'26626', '26542', '26531'},
       {'26592', '26588', '26580'}, {'26598', '26600', '26596'},
       {'26574', '26572'}, {'25742', '25741', '25739'},
       {'26521', '26542', '26531'},
       {'24305', '24352', '25966', '25965', '24307', '24306', '25955'},
       {'26600', '26595', '26596'}, {'26574'}, {'26564'},
       {'26544', '26545', '26563', '26562'},
       {'26644', '26664', '26663', '26662'},
       {'24754', '24755', '24753', '24752'}, {'24792', '24789', '24785'},
       {'26575', '26578'}, {'24618', '24619'},
       {'26623', '26622', '26612', '26625'},
       {'24783', '24772', '24775', '24774'},
       {'26752', '26753', '26785', '26765'}, {'24509', '24508', '24507'},
       {'24732', '24726', '24731', '24733'},
       {'26795', '26680', '26679', '26794'},
       {'24739', '24736', '24734', '24735'},
       {'26592', '26588', '26580', '26579'},
       {'26678', '26675', '26677', '26674'}, {'24740', '24750', '24751'},
       {'24635', '24634', '24636', '24637'},
       {'26598', '26600', '26595', '26596'},
       {'25931', '25929', '25935', '25925'},
       {'26673', '26670', '26671', '26672'}, {'26578', '26576'},
       {'26626', '26521', '26542', '26531'}, {'26569', '26564'},
       {'26577'}, {'26626', '26542', '26521'}, {'26577', '26576'},
       {'25988', '24313', '24310', '24311', '25985', '24312'},
       {'26575', '26576'}, {'25674', '25676', '25675'},
       {'24588', '24586', '24585', '24590'}, {'26575', '26578', '26576'},
       {'26544', '26563', '26562'},
       {'24320', '25992', '24321', '25989', '25991', '25990'},
       {'24588', '24586', '24585', '24590'}, {'26569', '26572', '26564'},
       {'25992', '24321', '25989', '25991', '25990', '24319'},
       {'25992', '24321', '25989', '25991', '24357', '25990', '24319'},
       {'24278', '26239', '24279', '26224', '26247', '26232', '24280', '24293'},
       {'25376', '25372', '25374'}, {'24591', '24593', '24592', '24594'},
       {'24796', '24797', '24795'},
       {'25988', '24313', '24310', '24311', '25987', '25986', '25985', '24312'},
       {'24584', '24565', '24566', '24583'}, {'26592', '26588', '26579'},
       {'26575'}, {'26598', '26600', '26595'}, {'26572'},
       {'26572', '26564'}, {'26588', '26580'},
       {'24306', '25955', '25966', '25965'}, {'26576'},
       {'26575', '26577', '26576'}, {'26578'}, {'26575', '26577'},
       {'24562', '24564', '24563', '24560'}, {'26578', '26577', '26576'},
       {'26575', '26578', '26577', '26576'}, {'26569', '26574', '26564'},
       {'24666', '24683', '24667'}, {'26598', '26595', '26596'},
       {'24309', '24296', '25984', '25968', '25967', '24277', '25983', '24308'},
       {'26575', '26577', '26578'}, {'24666', '24664', '24683', '24667'},
       {'25890', '25908', '25909', '25847'},
       {'25694', '25700', '25695', '25704'},
       {'26128', '26159', '26135', '26133'},
       {'25414', '25408', '24512', '25410'},
       {'25387', '25378', '25380', '25382'},
       {'25570', '25572', '25569', '25571'},
       {'25638', '25639', '25641', '25642'},
       {'26107', '26110', '26071', '26081'},
       {'25428', '25430', '25406', '25432'},
       {'25686', '25688', '25681', '25683'},
       {'25376', '25372', '25374', '25418'}, {'25503', '25553', '25564'},
       {'25742', '25741', '25739', '25740'},
       {'25643', '25665', '25663', '25664'},
       {'25426', '25420', '25424', '25422'},
       {'24643', '24645', '24644', '24642'},
       {'25667', '25674', '25676', '25675'},
       {'25403', '25392', '25416', '25391'},
       {'25585', '25605', '25587', '25584'},
       {'25690', '25724', '25692', '25689'},
       {'25937', '25939', '24300', '25938', '24295', '25943', '24294', '24297'},
       {'25566', '25565', '25567', '25568'},
       {'25435', '25434', '25436', '25485'}, {'25738', '25726'},
       {'25438', '25490', '25488', '25492'},
       {'25598', '25599', '25594', '25593'},
       {'25591', '25588', '25592', '25590'},
       {'25679', '25677', '25678', '25680'},
       {'26092', '26058', '26060', '26061'}, {'25725', '25707', '25708'},
       {'26207', '26205', '26204', '26216'},
       {'26174', '26203', '26181', '26202'},
       {'25573', '25578', '25575', '25576'}, {'26271', '26166', '26138'},
       {'26271', '26138', '26166', '26140'},
       {'24596', '24595', '24604', '24602'},
       {'26126', '26118', '26124', '26115'}, {'25738', '25726', '25732'},
       {'25903', '25911', '25891', '25892'},
       {'26771', '26767', '26768', '26772'},
       {'25912', '25913', '25904', '25914'},
       {'24639', '24641', '24638', '24640'},
       {'25997', '26002', '25994', '25993'}, {'26577', '26578'},
       {'25923', '25918', '25915'}, {'24518', '24525', '24523'},
       {'26744', '26730', '26745', '26724'},
       {'24793', '24796', '24797', '24795'},
       {'24648', '24647', '24651', '24646'},
       {'26641', '26642', '26643', '26640'}, {'26588', '26580', '26579'},
       {'24661', '24656', '24663', '24657'},
       {'24687', '24688', '24685', '24684'},
       {'25862', '25885', '25858', '25859'},
       {'24278', '24279', '26224', '26247', '26232', '24293'},
       {'24516', '24515', '24514', '24517'},
       {'26682', '26683', '26684', '26681'},
       {'24605', '24609', '24617', '24611'},
       {'24633', '24624', '24625', '24631'},
       {'24320', '25992', '24321', '25989', '25991', '24357', '25990', '24319'},
       {'25686', '25688', '25683'},
       {'25945', '24303', '24301', '25944', '24304', '24302', '25949'},
       {'24305', '24352', '25966', '25965', '24307', '24306', '25955', '25962'},
       {'26006', '26007', '26008', '26009'},
       {'25855', '25856', '25857', '25854'},
       {'26688', '26705', '26685', '26695'},
       {'26608', '26611', '26607', '26601'},
       {'24756', '24759', '24758', '24773'},
       {'24652', '24654', '24655', '24653'},
       {'25849', '25852', '25853', '25848'},
       {'26702', '26703', '26739', '26748'},
       {'26669', '26786', '26666', '26668'}, {'24618', '24619', '24623'},
       {'26574', '26564'}], dtype=object)

In [22]:
print(list(all_p))

['24596', '26679', '24514', '26159', '26672', '25848', '25410', '25967', '24657', '26642', '25962', '26678', '24293', '24296', '26626', '25931', '24586', '24773', '24633', '26205', '24308', '25642', '25391', '25708', '26668', '26663', '25692', '24754', '24584', '24609', '24307', '25503', '26644', '24793', '24300', '24305', '24617', '26008', '25738', '25991', '24278', '25925', '25567', '26271', '25588', '24277', '26588', '24509', '25592', '24651', '24752', '25584', '26598', '25639', '24785', '26688', '25856', '25857', '25664', '25859', '25681', '26607', '26071', '25576', '24655', '24310', '25418', '26579', '25414', '26124', '25937', '26666', '25380', '25571', '24648', '26702', '24634', '24753', '26795', '24736', '25726', '26007', '25739', '26596', '24605', '25565', '26685', '25740', '25593', '24732', '25966', '25912', '24774', '26006', '24312', '24303', '26675', '26670', '25566', '26542', '25665', '24731', '26608', '25990', '24640', '26641', '26544', '24566', '25683', '25986', '24684', '26092', '24508', '24280', '26216', '26794', '25382', '25403', '24683', '26207', '25847', '25943', '26174', '25849', '26572', '24795', '25430', '25406', '25598', '25594', '24583', '25904', '26580', '24653', '25605', '25643', '25994', '26203', '26060', '26110', '24624', '25428', '24631', '24740', '26625', '24311', '26643', '26133', '26771', '24306', '24796', '24564', '24302', '24563', '24663', '26684', '26622', '24733', '25553', '26744', '24734', '26058', '25674', '26562', '25676', '24516', '26753', '25724', '25488', '26739', '24517', '25997', '24772', '24301', '26695', '25852', '26673', '25853', '24739', '26640', '26564', '26009', '24357', '24611', '25688', '26595', '24602', '25914', '25892', '24297', '25890', '24515', '25580', '24625', '24685', '25923', '24797', '24507', '25704', '25680', '25983', '25591', '25911', '25854', '26575', '26118', '25694', '25992', '24638', '25938', '24647', '24636', '25700', '26681', '24645', '24641', '26181', '25903', '26703', '24304', '26611', '24637', '24646', '25432', '24593', '24590', '26705', '26140', '24595', '25918', '25955', '25968', '24644', '24320', '25939', '24592', '26545', '26166', '24642', '24518', '26683', '24755', '25695', '25578', '25690', '25641', '25855', '25677', '24604', '24594', '25568', '26662', '24735', '25372', '25485', '26748', '24775', '24750', '26204', '24623', '25435', '25929', '25587', '25993', '25564', '25438', '26521', '26765', '25913', '25376', '24661', '25426', '26677', '25985', '25599', '25573', '25862', '24309', '25490', '25915', '24313', '24565', '25965', '26081', '25732', '24523', '25583', '26135', '24726', '25570', '25908', '24321', '24512', '25424', '25422', '26002', '24792', '24525', '24295', '25944', '25579', '25987', '25374', '25667', '25725', '26745', '26531', '24789', '25387', '26767', '25891', '25686', '25436', '24294', '26669', '25678', '25675', '24664', '24619', '26126', '26107', '26600', '24588', '26786', '24352', '25378', '25707', '24783', '26671', '26612', '26730', '24279', '25392', '24667', '26202', '26601', '26768', '26232', '26623', '26576', '25569', '26569', '26574', '25989', '25581', '26682', '26664', '24319', '26674', '25949', '24759', '24751', '26752', '24756', '26724', '25420', '24656', '25689', '26224', '24643', '25984', '26115', '24562', '26061', '24585', '26128', '25572', '25663', '24688', '25742', '26239', '25988', '25575', '25679', '26785', '24639', '24687', '24618', '24560', '26592', '24666', '24652', '25858', '26138', '25945', '25935', '25638', '25585', '25434', '24758', '26578', '25416', '25492', '24654', '26680', '26577', '25590', '25909', '24591', '25741', '26247', '25885', '26772', '24635', '25408', '26563']